In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)


In [20]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 6, activation='relu' ))

ann.add(tf.keras.layers.Dense(units = 6, activation='relu' ))

ann.add(tf.keras.layers.Dense(units = 1))

In [21]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [22]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 18388.2012
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 361.2166
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 343.8184
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 323.5341
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 301.6349
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 278.2700
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 254.5805
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 231.1866
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 208.8101
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 187.5679
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 167.4233
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - lo

In [23]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.09 431.23]
 [463.18 460.01]
 [466.71 461.14]
 ...
 [473.91 473.26]
 [440.7  438.  ]
 [459.91 463.28]]
